name: i18nify-react Release

on:
  workflow_dispatch:
  push:

env:
  GITHUB_ACCESS_TOKEN: ${{ secrets.CI_BOT_TOKEN }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest # nosemgrep: non-self-hosted-runner
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node v20
        uses: actions/setup-node@v3
        with:
          node-version: 20.3.1
      - name: Install dependencies
        run: yarn
      - name: Create Release Pull Request & Publish packages
        id: changesets
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.CI_BOT_TOKEN }}
        with:
          publish: yarn release
          commit: 'build(i18nify-react): update version'
          title: 'build(i18nify-react): update version'
      - name: Publish to public npm registry
        env:
          NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
        run: yarn publish-npm
