name: i18nify-react Release

on:
  workflow_dispatch:
  push:

env:
  GITHUB_ACCESS_TOKEN: ${{ secrets.CI_BOT_TOKEN }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest # nosemgrep: non-self-hosted-runner
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node v20
        uses: actions/setup-node@v3
        with:
          node-version: 20.3.1
          registry-url: https://npm.pkg.github.com/
          scope: '@razorpay'
        env:
          NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
          GITHUB_ACCESS_TOKEN: ${{ secrets.CI_BOT_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.CI_BOT_TOKEN }}
      - name: Install dependencies
        run: yarn

      - name: view the secrets context
        shell: bash
        run: echo "$SECRETS_CONTEXT"
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}

      - name: Publish to public npm registry
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.github_token }}" > ~/.npmrc
          npm publish --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
          GITHUB_ACCESS_TOKEN: ${{ secrets.CI_BOT_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.CI_BOT_TOKEN }}
